spring.application.name=item-service
server.port=8082

#H2
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop

#PostgreQL
spring.datasource.url=jdbc:postgresql://localhost:5432/item
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Config server
spring.config.import=optional:configserver:http://localhost:8080;
#spring.profile.active=dev

#resilience4j
resilience4j.circuitbreaker.instances.categoryBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.categoryBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.categoryBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.categoryBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.categoryBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.categoryBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.categoryBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.categoryBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.categoryBreaker.sliding-window-type=count_based

resilience4j.circuitbreaker.instances.categoryBreaker.max-attempts=5
resilience4j.circuitbreaker.instances.categoryBreaker.wait-duration=2s

resilience4j.ratelimiter.instances.categoryBreaker.timeout-duration=0
resilience4j.ratelimiter.instances.categoryBreaker.limit-refresh-period=4
resilience4j.ratelimiter.instances.categoryBreaker.limit-for-period=2